#!/bin/sh

set -e

if ! [ $# = 0 ]; then
    echo "no args, stands for 'synchronize' and DOESN'T DEPLOY" >&2
    exit 1
fi

cd ..

(
    cd git-ignores
    mkdir -p deploy.gitig
    cd deploy.gitig
    if [ -e tmp-py ]; then rm -rf tmp-py; fi
    mkdir -p tmp-py/db python static sys
)

d=git-ignores/deploy.gitig

rsync python/*.py $d/tmp-py/
rsync python/*.ini $d/tmp-py/
rsync python/db/*.py $d/tmp-py/db/
rsync -r --delete $d/tmp-py/ $d/python/
rm -r $d/tmp-py
rsync -r --delete git-ignores/front-static-serve.gitig/ $d/static/
rsync -r --delete server-scripts/ $d/sys/

. sys/secrets.gitig.sh

echo "rsync to remote..."
rsync -rz --delete $d/ "$secret_upload"/

echo "done"
