#!/bin/sh

(
    cd ./python
    . venv/bin/activate
    export KEYMOUTH_RAM_DB=yes
    export KEYMOUTH_INTTEST_WIDGETS=yes
    timeout 2.2s uvicorn                        \
            --host localhost                    \
            --port 8001                         \
            --log-config systest-log-config.ini \
            main:app
) &

sleep 1.2

(
    export KEYMOUTH_UI=the-ui-uri-isnt-used
    export KEYMOUTH_API=http://localhost:8001
    export KEYMOUTH_WS=ws://localhost:8001

    timeout 1s node js/mod/ControllerInttestMain.js
    echo $? > git-ignores/systest-front-result.gitig
) &

wait

python python/systest_check.py || exit 1
r="$(head git-ignores/systest-front-result.gitig)"
echo "the front end returned $r"
exit "$r"
