#!/bin/sh

f=git-ignores/test-result-expect-all-0.gitig
cd ..
: > $f

echo
echo " ===  front end tests  ==="
echo
echo js/mod/EventPresenter.test.js
node js/mod/EventPresenter.test.js
echo $? >> $f
echo js/mod/accumulateDiffs.test.js
node js/mod/accumulateDiffs.test.js
echo $? >> $f
echo
echo " ===  back end tests  ==="
echo
python python/AfterSocketLogicTest.py
echo $? >> $f
echo
echo " ===  non-db integration tests  ==="
echo
sh sys/test-front-back-integ
echo $? >> $f

test 0 = "$(awk '{s += $0} END {print s}' $f)" || exit 1
