#!/bin/sh

set -e

usage="Usage: $0 ARGS

ARGS:
  -t  start the tmux session
  -i  use the IP address instead of localhost, for mobile tests
  -d  start server and client in watch mode
  -e  open emacs configured
  -a  attach tmux session

Examples:
  $0 -tidea  at home
  $0 -tdea   in the library
  $0 -tiea   at times
"

usage_and_exit() {
    printf "%s\n" "$usage" >& 2
    exit 1
}

if [ $# = 0 ]; then usage_and_exit; fi
getopt_res="$(getopt -o tidea -- "$@")" || usage_and_exit
eval set -- "$getopt_res"

ip=localhost

main() {
    while ! [ "x$1" = x-- ]; do
        case "$1" in
            -t) tmux new-session -d -t key-mouth ;;
            -i) ip="$(ip addr | sed -n 's|.*inet \(.*\)/24.*|\1|p')" ;;
            -d) start_front && start_back && start_firefox ;;
            -e) start_emacs ;;
            -a) attach_tmux ;;
        esac
        shift
    done
}

_tsk1() { tmux send-keys -t key-mouth:1 "$@" C-m; }
_tsk2() { tmux send-keys -t key-mouth:2 "$@" C-m; }

start_front() {
    tmux new-window -t key-mouth:1
    _tsk1 "export KEYMOUTH_UI=http://$ip:3000"
    _tsk1 "export KEYMOUTH_API=http://$ip:8000"
    _tsk1 "export KEYMOUTH_WS=ws://$ip:8000"
    _tsk1 "export KEYMOUTH_MAX_PAGES=3"
    _tsk1 "cd js"
    _tsk1 "npm run dev"
}

start_back() {
    tmux new-window -t key-mouth:2
    _tsk2 "cd python"
    _tsk2 ". venv/bin/activate"
    _tsk2 "export KEYMOUTH_RAM_DB=yes"
    _tsk2 "export KEYMOUTH_CORS_ALL=yes"
    _tsk2 "export KEYMOUTH_ADD_A_ROOM=yes"
    _tsk2 "export KEYMOUTH_MOMENTS_PER_PAGE=3"
    _tsk2 "uvicorn main:app --host $ip --port 8000 --reload"
}

start_firefox() {
    bspc rule --add 'firefox:*:*' --one-shot desktop=^2
    (firefox $ip:3000 2>&1 \
         | grep --line-buffered -v mesa_glthread \
                > git-ignores/logs-firefox.gitig) &
}

start_emacs() {
    bspc rule --add '*:emacs:*' --one-shot desktop=^1
    tmux new-window -t key-mouth:3
    tmux send-keys  -t key-mouth:3 ". python/venv/bin/activate" C-m
    tmux send-keys  -t key-mouth:3 "emacs" C-m
}

attach_tmux() {
    tmux select-window -t key-mouth:0
    tmux attach-session -t key-mouth
}

main "$@"
