#!/bin/sh

set -e

if ! [ $# = 0 ]; then
    echo "no args, test and deploy" >&2
    exit 1
fi

. ./secrets.gitig.sh

cd "$secret_uploaded"/python
. "$secret_venv"/bin/activate
python run_unit_tests.py
python db_test.py

if ! [ "x$*" = "xn" ]; then
    secret_kill_old_with kill -s TERM
    secret_wrapper uvicorn main:app
fi

echo "done"
